version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: namedb
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@mail.com
      PGADMIN_DEFAULT_PASSWORD: mdp
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
  pgadmin_data: